# Generated by Django 3.0.6 on 2022-08-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.TextField(max_length=10)),
                ('FirstName', models.TextField(max_length=255, unique=True)),
                ('LastName', models.TextField(max_length=100, unique=True)),
                ('username', models.TextField(max_length=200, unique=True)),
                ('Password', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do', models.FloatField()),
                ('bod', models.FloatField()),
                ('tcb', models.FloatField()),
                ('fcb', models.FloatField()),
                ('nh3n', models.FloatField()),
                ('classification', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Water_Basic_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_source_name', models.TextField()),
                ('province_name', models.TextField()),
                ('area_size', models.TextField()),
                ('water_source_characteristics', models.TextField()),
                ('water_source_information', models.TextField()),
                ('picture_water', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.IntegerField()),
                ('picture_water', models.ImageField(upload_to='images')),
                ('waterbasic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.Water_Basic_Data')),
            ],
        ),
    ]
